// <auto-generated />
using System;
using Infraestructura.Repositorios.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(StellarMindsContext))]
    partial class StellarMindsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.AuditoriaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<int>("CoordinadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("AuditoriasPrestamo");
                });

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("TipoEquipo").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entidades.ObjetoCeleste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ObjetosCelestes");
                });

            modelBuilder.Entity("Dominio.Entidades.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaObservacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjetoCelesteId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int?>("Resultado")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetoCelesteId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Observaciones", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CamaraId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonturaId")
                        .HasColumnType("int");

                    b.Property<int?>("OcularId")
                        .HasColumnType("int");

                    b.Property<int>("TelescopioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamaraId");

                    b.HasIndex("MonturaId");

                    b.HasIndex("OcularId");

                    b.HasIndex("TelescopioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("TipoRol")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoRol").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoCamara", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Equipo");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoMontura", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Equipo");

                    b.Property<bool>("EsGoTo")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMontura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoOcular", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Equipo");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoTelescopio", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Equipo");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("Dominio.Entidades.Administrador", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Dominio.Entidades.Coordinador", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Coordinador");
                });

            modelBuilder.Entity("Dominio.Entidades.Socio", b =>
                {
                    b.HasBaseType("Dominio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("Dominio.Entidades.AuditoriaPrestamo", b =>
                {
                    b.HasOne("Dominio.Entidades.Usuario", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coordinador");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOCantidadDisponible", "CantidadDisponible", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOMarca", "Marca", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOModelo", "Modelo", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.Navigation("CantidadDisponible")
                        .IsRequired();

                    b.Navigation("Marca")
                        .IsRequired();

                    b.Navigation("Modelo")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.ObjetoCeleste", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOShared.VONombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("ObjetoCelesteId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ObjetoCelesteId");

                            b1.ToTable("ObjetosCelestes");

                            b1.WithOwner()
                                .HasForeignKey("ObjetoCelesteId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOObjetoCeleste.VOMagnitudAparente", "MagnitudAparente", b1 =>
                        {
                            b1.Property<int>("ObjetoCelesteId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ObjetoCelesteId");

                            b1.ToTable("ObjetosCelestes");

                            b1.WithOwner()
                                .HasForeignKey("ObjetoCelesteId");
                        });

                    b.Navigation("MagnitudAparente")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.Observacion", b =>
                {
                    b.HasOne("Dominio.Entidades.ObjetoCeleste", "ObjetoCeleste")
                        .WithMany()
                        .HasForeignKey("ObjetoCelesteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dominio.ValueObjects.VOObservacion.VODetalle", "Detalle", b1 =>
                        {
                            b1.Property<int>("ObservacionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Detalle");

                            b1.HasKey("ObservacionId");

                            b1.ToTable("Observaciones");

                            b1.WithOwner()
                                .HasForeignKey("ObservacionId");
                        });

                    b.Navigation("Detalle");

                    b.Navigation("ObjetoCeleste");

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entidades.Prestamo", b =>
                {
                    b.HasOne("Dominio.Entidades.EquipoCamara", "Camara")
                        .WithMany()
                        .HasForeignKey("CamaraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dominio.Entidades.EquipoMontura", "Montura")
                        .WithMany()
                        .HasForeignKey("MonturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.EquipoOcular", "Ocular")
                        .WithMany()
                        .HasForeignKey("OcularId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dominio.Entidades.EquipoTelescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("TelescopioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Camara");

                    b.Navigation("Montura");

                    b.Navigation("Ocular");

                    b.Navigation("Telescopio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOShared.VONombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VOApellido", "Apellido", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VOContrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VODireccion", "Direccion", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VOEmail", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VONombreUsuario", "NombreUsuario", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOUsuario.VOTelefono", "Telefono", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Apellido")
                        .IsRequired();

                    b.Navigation("Contrasenia")
                        .IsRequired();

                    b.Navigation("Direccion")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("NombreUsuario")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoCamara", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOResolucion", "Resolucion", b1 =>
                        {
                            b1.Property<int>("EquipoCamaraId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EquipoCamaraId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoCamaraId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOTamanioPixelMicras", "TamanioPixelMicras", b1 =>
                        {
                            b1.Property<int>("EquipoCamaraId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoCamaraId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoCamaraId");
                        });

                    b.Navigation("Resolucion")
                        .IsRequired();

                    b.Navigation("TamanioPixelMicras")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoMontura", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOUnidadKg", "CargaUtilKg", b1 =>
                        {
                            b1.Property<int>("EquipoMonturaId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoMonturaId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoMonturaId");
                        });

                    b.Navigation("CargaUtilKg")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoOcular", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOUnidadMM", "DiametroMM", b1 =>
                        {
                            b1.Property<int>("EquipoOcularId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoOcularId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoOcularId");
                        });

                    b.OwnsOne("VOAnguloVisionGrado", "AnguloVisionGrados", b1 =>
                        {
                            b1.Property<int>("EquipoOcularId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoOcularId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoOcularId");
                        });

                    b.Navigation("AnguloVisionGrados")
                        .IsRequired();

                    b.Navigation("DiametroMM")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.EquipoTelescopio", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOUnidadMM", "AperturaMM", b1 =>
                        {
                            b1.Property<int>("EquipoTelescopioId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoTelescopioId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoTelescopioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOUnidadMM", "DistanciaFocalMM", b1 =>
                        {
                            b1.Property<int>("EquipoTelescopioId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoTelescopioId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoTelescopioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VOUnidadKg", "PesoKg", b1 =>
                        {
                            b1.Property<int>("EquipoTelescopioId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("EquipoTelescopioId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoTelescopioId");
                        });

                    b.OwnsOne("Dominio.ValueObjects.VOEquipo.VORelacionFocal", "RelacionFocal", b1 =>
                        {
                            b1.Property<int>("EquipoTelescopioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EquipoTelescopioId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoTelescopioId");
                        });

                    b.Navigation("AperturaMM")
                        .IsRequired();

                    b.Navigation("DistanciaFocalMM")
                        .IsRequired();

                    b.Navigation("PesoKg")
                        .IsRequired();

                    b.Navigation("RelacionFocal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
